export const questoes = [
  {
    id: "q1",
    instituicao: "IF",
    prova: "IF 2023",
    materia: "Matemática",
    assunto: "Equações",
    dificuldade: "medio",
    pergunta: "Qual o valor de x em 2x + 4 = 10?",
    alternativas: ["2", "3", "4", "5"],
    correta: 1,
    dica: "Isolar o x subtraindo 4 de ambos os lados",
    resolucao: "2x + 4 = 10 → 2x = 10 - 4 → 2x = 6 → x = 3"
  },
  {
    id: "q2",
    instituicao: "ENEM",
    prova: "ENEM 2022",
    materia: "Matemática",
    assunto: "Porcentagem",
    dificuldade: "facil",
    pergunta: "10% de 200 é:",
    alternativas: ["10", "20", "30", "40"],
    correta: 1,
    dica: "Multiplique o valor por 0,10",
    resolucao: "200 × 0,10 = 20"
  },
  {
    id: "q3",
    instituicao: "IF",
    prova: "IF 2022",
    materia: "Matemática",
    assunto: "Razão e Proporção",
    dificuldade: "medio",
    pergunta: "Se 2 lápis custam R$4, quanto custam 5 lápis?",
    alternativas: ["R$8", "R$9", "R$10", "R$12"],
    correta: 2,
    dica: "Primeiro descubra o preço unitário",
    resolucao: "Cada lápis custa R$2 (4÷2) → 5 × 2 = R$10"
  },
  {
    id: "q4",
    instituicao: "ENEM",
    prova: "ENEM 2023",
    materia: "Português",
    assunto: "Interpretação",
    dificuldade: "facil",
    pergunta: "O objetivo principal de um texto informativo é:",
    alternativas: ["Convencer o leitor", "Informar sobre um tema", "Emocionar o leitor", "Narrar uma história"],
    correta: 1,
    dica: "Pense na função comunicativa do texto",
    resolucao: "Textos informativos têm como função principal transmitir informações de forma clara e objetiva."
  },
  {
    id: "q5",
    instituicao: "IF",
    prova: "IF 2023",
    materia: "Português",
    assunto: "Classes gramaticais",
    dificuldade: "medio",
    pergunta: "Qual alternativa contém apenas substantivos?",
    alternativas: ["Casa, beleza, coragem", "Correr, falar, amar", "Bonito, alto, forte", "Rapidamente, ontem, hoje"],
    correta: 0,
    dica: "Substantivos nomeiam seres, objetos, sentimentos ou qualidades",
    resolucao: "Casa (substantivo concreto), beleza e coragem (substantivos abstratos). As outras opções contêm verbos, adjetivos e advérbios."
  },
  {
    id: "q6",
    instituicao: "ENEM",
    prova: "ENEM 2022",
    materia: "História",
    assunto: "Brasil Colônia",
    dificuldade: "medio",
    pergunta: "Qual foi o principal produto explorado no início da colonização portuguesa no Brasil?",
    alternativas: ["Ouro", "Café", "Pau-brasil", "Açúcar"],
    correta: 2,
    dica: "Este produto deu nome ao nosso país",
    resolucao: "O pau-brasil foi o primeiro produto explorado pelos portugueses (1500-1530), usado para tingir tecidos na Europa."
  },
  {
    id: "q7",
    instituicao: "IF",
    prova: "IF 2022",
    materia: "História",
    assunto: "Idade Média",
    dificuldade: "facil",
    pergunta: "O sistema feudal era baseado principalmente em:",
    alternativas: ["Indústria e manufatura", "Comércio marítimo", "Posse de terras", "Tecnologia avançada"],
    correta: 2,
    dica: "Os senhores feudais eram donos de grandes extensões",
    resolucao: "O feudalismo tinha como base a posse de terras (feudos), onde os senhores feudais exerciam poder sobre os servos."
  },
  {
    id: "q8",
    instituicao: "ENEM",
    prova: "ENEM 2023",
    materia: "Geografia",
    assunto: "Climas do Brasil",
    dificuldade: "medio",
    pergunta: "O clima predominante na região Norte do Brasil é:",
    alternativas: ["Equatorial", "Tropical", "Semiárido", "Subtropical"],
    correta: 0,
    dica: "Esta região está próxima à linha do Equador",
    resolucao: "O clima equatorial caracteriza-se por altas temperaturas e chuvas abundantes durante todo o ano, típico da Amazônia."
  },
  {
    id: "q9",
    instituicao: "IF",
    prova: "IF 2023",
    materia: "Geografia",
    assunto: "Cartografia",
    dificuldade: "facil",
    pergunta: "A escala de um mapa serve para:",
    alternativas: ["Indicar o clima da região", "Mostrar a vegetação", "Representar a proporção entre o mapa e a realidade", "Indicar o relevo"],
    correta: 2,
    dica: "Relaciona o tamanho no mapa com o tamanho real",
    resolucao: "A escala indica quantas vezes o espaço real foi reduzido no mapa. Ex: 1:100.000 significa que 1cm no mapa = 100.000cm na realidade."
  },
  {
    id: "q10",
    instituicao: "ENEM",
    prova: "ENEM 2022",
    materia: "Ciências",
    assunto: "Sistema Solar",
    dificuldade: "facil",
    pergunta: "Qual planeta é conhecido como 'planeta vermelho'?",
    alternativas: ["Marte", "Júpiter", "Vênus", "Mercúrio"],
    correta: 0,
    dica: "Sua cor vem do óxido de ferro em sua superfície",
    resolucao: "Marte é chamado de planeta vermelho devido à presença de óxido de ferro (ferrugem) em sua superfície."
  },
  {
    id: "q11",
    instituicao: "IF",
    prova: "IF 2022",
    materia: "Ciências",
    assunto: "Corpo Humano",
    dificuldade: "medio",
    pergunta: "Qual órgão é responsável por bombear o sangue para todo o corpo?",
    alternativas: ["Pulmão", "Fígado", "Coração", "Rim"],
    correta: 2,
    dica: "É um músculo que bate cerca de 100.000 vezes por dia",
    resolucao: "O coração é o órgão central do sistema circulatório, responsável por bombear sangue oxigenado para todo o organismo."
  },
  {
    id: "q12",
    instituicao: "ENEM",
    prova: "ENEM 2023",
    materia: "Matemática",
    assunto: "Frações",
    dificuldade: "medio",
    pergunta: "Qual é o resultado de 1/2 + 1/4?",
    alternativas: ["1/4", "2/4", "3/4", "1"],
    correta: 2,
    dica: "Encontre o denominador comum primeiro",
    resolucao: "1/2 = 2/4, então 2/4 + 1/4 = 3/4"
  },
  {
    id: "q13",
    instituicao: "IF",
    prova: "IF 2023",
    materia: "Matemática",
    assunto: "Potenciação",
    dificuldade: "facil",
    pergunta: "Quanto é 2²?",
    alternativas: ["2", "4", "6", "8"],
    correta: 1,
    dica: "Multiplique a base por ela mesma",
    resolucao: "2² = 2 × 2 = 4"
  },
  {
    id: "q14",
    instituicao: "ENEM",
    prova: "ENEM 2022",
    materia: "Matemática",
    assunto: "Equação do 2º grau",
    dificuldade: "dificil",
    pergunta: "As soluções de x² − 4 = 0 são:",
    alternativas: ["x = 4", "x = −4", "x = ±2", "x = 0"],
    correta: 2,
    dica: "Isole x² e depois tire a raiz quadrada",
    resolucao: "x² = 4 → x = ±√4 → x = ±2 (ou seja, x = 2 ou x = -2)"
  },
  {
    id: "q15",
    instituicao: "IF",
    prova: "IF 2022",
    materia: "Português",
    assunto: "Ortografia",
    dificuldade: "medio",
    pergunta: "Qual palavra está escrita corretamente?",
    alternativas: ["Excessão", "Exceção", "Excessao", "Excessám"],
    correta: 1,
    dica: "Palavras terminadas em -ção geralmente vêm de verbos",
    resolucao: "Exceção é a grafia correta. Vem do latim 'exceptio' e significa algo fora da regra."
  },
  {
    id: "q16",
    instituicao: "ENEM",
    prova: "ENEM 2023",
    materia: "Português",
    assunto: "Pontuação",
    dificuldade: "facil",
    pergunta: "Qual sinal de pontuação indica uma pergunta?",
    alternativas: ["!", ".", "?", ","],
    correta: 2,
    dica: "Usado ao final de frases interrogativas",
    resolucao: "O ponto de interrogação (?) é usado para indicar perguntas diretas."
  },
  {
    id: "q17",
    instituicao: "IF",
    prova: "IF 2023",
    materia: "História",
    assunto: "Independência do Brasil",
    dificuldade: "medio",
    pergunta: "Em que ano ocorreu a Independência do Brasil?",
    alternativas: ["1808", "1822", "1889", "1500"],
    correta: 1,
    dica: "Foi proclamada por D. Pedro I às margens do Rio Ipiranga",
    resolucao: "A Independência do Brasil foi proclamada em 7 de setembro de 1822 por D. Pedro I."
  },
  {
    id: "q18",
    instituicao: "ENEM",
    prova: "ENEM 2022",
    materia: "Geografia",
    assunto: "População",
    dificuldade: "medio",
    pergunta: "O crescimento populacional natural ocorre quando:",
    alternativas: ["Há mais mortes que nascimentos", "Nascimentos = mortes", "Há mais nascimentos que mortes", "Não há migração"],
    correta: 2,
    dica: "Relaciona taxa de natalidade e mortalidade",
    resolucao: "O crescimento vegetativo/natural é positivo quando a taxa de natalidade supera a taxa de mortalidade."
  },
  {
    id: "q19",
    instituicao: "IF",
    prova: "IF 2022",
    materia: "Ciências",
    assunto: "Ecologia",
    dificuldade: "medio",
    pergunta: "Qual é a função dos produtores em uma cadeia alimentar?",
    alternativas: ["Consumir outros seres", "Produzir seu próprio alimento", "Decompor matéria orgânica", "Controlar a população"],
    correta: 1,
    dica: "São geralmente organismos fotossintetizantes",
    resolucao: "Produtores (plantas, algas) realizam fotossíntese, produzindo seu próprio alimento e iniciando a cadeia alimentar."
  },
  {
    id: "q20",
    instituicao: "ENEM",
    prova: "ENEM 2023",
    materia: "Ciências",
    assunto: "Química Básica",
    dificuldade: "facil",
    pergunta: "A fórmula química da água é:",
    alternativas: ["H₂O", "CO₂", "O₂", "NaCl"],
    correta: 0,
    dica: "Composta por hidrogênio e oxigênio",
    resolucao: "H₂O significa 2 átomos de hidrogênio ligados a 1 átomo de oxigênio."
  },
  {
    id: "q21",
    instituicao: "IF",
    prova: "IF 2023",
    materia: "Matemática",
    assunto: "Média Aritmética",
    dificuldade: "medio",
    pergunta: "A média aritmética de 4, 6 e 8 é:",
    alternativas: ["5", "6", "7", "8"],
    correta: 1,
    dica: "Some todos os valores e divida pela quantidade",
    resolucao: "(4 + 6 + 8) ÷ 3 = 18 ÷ 3 = 6"
  },
  {
    id: "q22",
    instituicao: "ENEM",
    prova: "ENEM 2022",
    materia: "Matemática",
    assunto: "Geometria",
    dificuldade: "medio",
    pergunta: "Quantos lados tem um hexágono?",
    alternativas: ["4", "5", "6", "8"],
    correta: 2,
    dica: "O prefixo 'hexa' indica o número de lados",
    resolucao: "Hexa = seis. O hexágono é um polígono de 6 lados."
  },
  {
    id: "q23",
    instituicao: "IF",
    prova: "IF 2022",
    materia: "Português",
    assunto: "Figuras de linguagem",
    dificuldade: "dificil",
    pergunta: "A repetição de sons consonantais é chamada de:",
    alternativas: ["Metáfora", "Aliteração", "Hipérbole", "Ironia"],
    correta: 1,
    dica: "Comum em trava-línguas e poesias",
    resolucao: "Aliteração é a repetição de sons consonantais. Ex: 'O rato roeu a roupa do rei de Roma'."
  },
  {
    id: "q24",
    instituicao: "ENEM",
    prova: "ENEM 2023",
    materia: "História",
    assunto: "República",
    dificuldade: "medio",
    pergunta: "A Proclamação da República no Brasil ocorreu em:",
    alternativas: ["1822", "1889", "1930", "1964"],
    correta: 1,
    dica: "Foi liderada pelo Marechal Deodoro da Fonseca",
    resolucao: "A República foi proclamada em 15 de novembro de 1889, pondo fim ao Império de D. Pedro II."
  },
  {
    id: "q25",
    instituicao: "IF",
    prova: "IF 2023",
    materia: "Geografia",
    assunto: "Relevo",
    dificuldade: "facil",
    pergunta: "Montanhas, planaltos e planícies são exemplos de:",
    alternativas: ["Climas", "Vegetação", "Relevo", "Hidrografia"],
    correta: 2,
    dica: "São formas da superfície terrestre",
    resolucao: "Relevo é o conjunto de formas da superfície terrestre, incluindo montanhas, planaltos, planícies e depressões."
  },
  {
    id: "q26",
    instituicao: "ENEM",
    prova: "ENEM 2022",
    materia: "Ciências",
    assunto: "Física Básica",
    dificuldade: "medio",
    pergunta: "Qual unidade de medida representa a força no Sistema Internacional?",
    alternativas: ["Metro (m)", "Watt (W)", "Newton (N)", "Joule (J)"],
    correta: 2,
    dica: "Homenageia o cientista que estudou a gravidade",
    resolucao: "O Newton (N) é a unidade de força no SI, em homenagem a Isaac Newton."
  },
  {
    id: "q27",
    instituicao: "IF",
    prova: "IF 2022",
    materia: "Matemática",
    assunto: "Regra de três",
    dificuldade: "medio",
    pergunta: "Se 3 cadernos custam R$15, quanto custam 6 cadernos?",
    alternativas: ["R$20", "R$25", "R$30", "R$35"],
    correta: 2,
    dica: "Use a proporcionalidade direta",
    resolucao: "3 cadernos = R$15, então 1 caderno = R$5. Logo, 6 cadernos = 6 × R$5 = R$30"
  },
  {
    id: "q28",
    instituicao: "ENEM",
    prova: "ENEM 2023",
    materia: "Português",
    assunto: "Sinônimos",
    dificuldade: "facil",
    pergunta: "Qual é sinônimo de 'feliz'?",
    alternativas: ["Triste", "Alegre", "Bravo", "Cansado"],
    correta: 1,
    dica: "Significa o mesmo que contente",
    resolucao: "Alegre é sinônimo de feliz, ambos expressam estado de contentamento."
  },
  {
    id: "q29",
    instituicao: "IF",
    prova: "IF 2023",
    materia: "História",
    assunto: "Pré-História",
    dificuldade: "facil",
    pergunta: "A Pré-História termina com:",
    alternativas: ["Descoberta do fogo", "Invenção da escrita", "Início da Idade Média", "Revolução Industrial"],
    correta: 1,
    dica: "É o marco que divide Pré-História e História",
    resolucao: "A invenção da escrita (cerca de 4000 a.C.) marca o fim da Pré-História e início da História."
  },
  {
    id: "q30",
    instituicao: "ENEM",
    prova: "ENEM 2022",
    materia: "Ciências",
    assunto: "Biologia Molecular",
    dificuldade: "dificil",
    pergunta: "Qual molécula armazena a informação genética nos seres vivos?",
    alternativas: ["RNA", "ATP", "DNA", "Proteína"],
    correta: 2,
    dica: "Tem formato de dupla hélice",
    resolucao: "O DNA (Ácido Desoxirribonucleico) armazena toda a informação genética, organizado em genes e cromossomos."
  },
  {
    id: "q31",
    instituicao: "IF",
    prova: "IF 2023",
    materia: "Matemática",
    assunto: "Probabilidade",
    dificuldade: "dificil",
    pergunta: "Ao lançar uma moeda e um dado simultaneamente, qual a probabilidade de sair cara e número par?",
    alternativas: ["1/2", "1/4", "1/6", "1/12"],
    correta: 1,
    dica: "Multiplique as probabilidades individuais",
    resolucao: "P(cara) = 1/2, P(par) = 3/6 = 1/2. P(cara E par) = 1/2 × 1/2 = 1/4"
  },
  {
    id: "q32",
    instituicao: "ENEM",
    prova: "ENEM 2023",
    materia: "Ciências",
    assunto: "Termodinâmica",
    dificuldade: "muito_dificil",
    pergunta: "Em qual escala termométrica a água ferve a 373K?",
    alternativas: ["Celsius", "Fahrenheit", "Kelvin", "Réaumur"],
    correta: 2,
    dica: "É a escala absoluta usada em física",
    resolucao: "Na escala Kelvin, a água ferve a 373K (equivalente a 100°C). K = °C + 273"
  },
  {
    id: "q33",
    instituicao: "IF",
    prova: "IF 2022",
    materia: "Português",
    assunto: "Concordância",
    dificuldade: "dificil",
    pergunta: "Qual frase está com a concordância verbal correta?",
    alternativas: ["Fazem dois anos que não viajo", "Houveram muitos acidentes", "Existem várias soluções", "Haviam pessoas na sala"],
    correta: 2,
    dica: "O verbo deve concordar com o sujeito",
    resolucao: "'Existem várias soluções' - o verbo 'existir' concorda com o sujeito 'soluções'. 'Fazer' e 'haver' no sentido de tempo são impessoais."
  },
  {
    id: "q34",
    instituicao: "ENEM",
    prova: "ENEM 2022",
    materia: "Geografia",
    assunto: "Globalização",
    dificuldade: "medio",
    pergunta: "A globalização intensificou principalmente:",
    alternativas: ["O isolamento entre países", "O fluxo de mercadorias e informações", "A diminuição do comércio", "O fim das multinacionais"],
    correta: 1,
    dica: "Pense nas conexões internacionais atuais",
    resolucao: "A globalização intensificou os fluxos comerciais, financeiros e de informação entre países, criando interdependência global."
  },
  {
    id: "q35",
    instituicao: "IF",
    prova: "IF 2023",
    materia: "História",
    assunto: "Revolução Industrial",
    dificuldade: "medio",
    pergunta: "A Revolução Industrial teve início em qual país?",
    alternativas: ["França", "Alemanha", "Inglaterra", "Estados Unidos"],
    correta: 2,
    dica: "Este país foi pioneiro nas fábricas têxteis",
    resolucao: "A Revolução Industrial começou na Inglaterra no século XVIII, com a mecanização da indústria têxtil."
  }
];

// Funções auxiliares para extrair dados únicos
export const getMaterias = () => [...new Set(questoes.map(q => q.materia))];
export const getAssuntos = (materia) => [...new Set(questoes.filter(q => !materia || q.materia === materia).map(q => q.assunto))];
export const getInstituicoes = () => [...new Set(questoes.filter(q => q.instituicao).map(q => q.instituicao))];
export const getProvas = (instituicao) => [...new Set(questoes.filter(q => q.prova && (!instituicao || q.instituicao === instituicao)).map(q => q.prova))];

export const XP_POR_DIFICULDADE = {
  facil: 10,
  medio: 20,
  dificil: 30,
  muito_dificil: 50
};

export const DIFICULDADE_LABELS = {
  facil: { label: "Fácil", color: "bg-emerald-100 text-emerald-700 border-emerald-200" },
  medio: { label: "Médio", color: "bg-amber-100 text-amber-700 border-amber-200" },
  dificil: { label: "Difícil", color: "bg-orange-100 text-orange-700 border-orange-200" },
  muito_dificil: { label: "Muito Difícil", color: "bg-red-100 text-red-700 border-red-200" }
};